version: '3.8'

services:
  validator:
    build:
      context: .
      args:
        USER: validator
        USER_ID: 1000
        GROUP_ID: 1000
    ports:
      - "5000:5000"
    volumes:
      - validator_data:/app/data
      - validator_logs:/app/logs
    environment:
      - BITCOIN_RPC_HOST=bitcoin
      - BITCOIN_RPC_PORT=18443
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER:-user}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD:-password}
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - PYTHONPATH=/app
    depends_on:
      - bitcoin
    networks:
      - validator_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bitcoin:
    image: ruimarinho/bitcoin-core:latest
    command:
      -regtest=1
      -server=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=${BITCOIN_RPC_USER:-user}
      -rpcpassword=${BITCOIN_RPC_PASSWORD:-password}
      -fallbackfee=0.0002
      -txindex=1
      -debug=1
      -printtoconsole=1
    ports:
      - "18443:18443"
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
    networks:
      - validator_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "getblockchaininfo"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  validator_net:
    driver: bridge

volumes:
  validator_data:
    driver: local
  validator_logs:
    driver: local
  bitcoin_data:
    driver: local 